export type Source = {
  id: string;
  title: string;
  type: string;
  author: string;
  publisher: string;
  language: string;
  url: string;
  terms: string;
  scope: string;
  editionId: string;
  version: string;
  retrieved: string;
  checksum: string;
  status: string;
  count: number;
  metadata: string;
};
export type Passage = {
  id: string;
  edition_id: string;
  kind: string;
  key: string;
  surah: number | null;
  ayah: number | null;
  language: string;
  text: string;
  footnotes: string;
  checksum: string;
  url: string;
  sourceTitle: string;
  author: string;
  publisher: string;
  version: string;
  sourceId: string;
  rangeKeys?: string[];
  grade?: string;
  gradeAttribution?: string;
  reference?: string;
  arabic?: string;
  hints?: string[];
  glossary?: { word: string; meaning: string }[];
  relevance?: string;
};
export type Verse = {
  key: string;
  surah: number;
  ayah: number;
  text: string;
  basmalah: string | null;
  juz: number;
  page: number;
  edition_id: string;
  checksum: string;
  translations: Passage[];
};
export type Chapter = {
  surah: {
    id: number;
    name: string;
    arabic: string;
    meaning: string;
    count: number;
    revelation: string;
  };
  verses: Verse[];
  pages: {
    id: string;
    section: string;
    images: string;
    source_url: string;
    start_ayah: number;
    end_ayah: number;
  }[];
};
export type Evidence = {
  preferredTranslations?: Partial<Record<"en" | "bn" | "ja", string>>;
  id: string;
  key: string;
  kind: string;
  arabic?: string;
  verse?: Verse;
  passage?: Passage;
  related: Passage[];
  context?: Verse[];
  citation: {
    id: string;
    edition: string;
    locator: string;
    url: string;
    checksum: string;
    text: string;
    retrieved?: string;
  };
};
export type SearchResult = {
  id: string;
  key: string;
  kind: string;
  title: string;
  text: string;
  language: string;
  relevance: string;
  sourceTitle: string;
  url: string;
  score: number;
  grade?: string;
};
export type Research = {
  query: string;
  terms: string[];
  topics: string[];
  results: SearchResult[];
  total: number;
  page: number;
  pageSize: number;
  counts: Record<string, number>;
  coverage: { ayat: number; editions: number; hadith: number };
  scope: string;
  limitations: string[];
};
export type SavedEvidence = {
  id: string;
  evidence: Evidence;
  note: string;
  collection: string;
  savedAt: string;
  order: number;
};
export type Talk = {
  title: string;
  language: "en" | "bn" | "ja";
  audience: string;
  minutes: number;
  outline: string;
  draft: string;
  evidenceIds: string[];
  updated: string;
};
